// Mocks generated by Mockito 5.4.6 from annotations
// in chat_ai_offline/test/mocks/llama_mock.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;

import 'package:llama_flutter_android/src/llama_api.dart' as _i2;
import 'package:llama_flutter_android/src/llama_controller.dart' as _i3;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakeContextInfo_0 extends _i1.SmartFake implements _i2.ContextInfo {
  _FakeContextInfo_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [LlamaController].
///
/// See the documentation for Mockito's code generation for more information.
class MockLlamaController extends _i1.Mock implements _i3.LlamaController {
  @override
  _i4.Stream<double> get loadProgress => (super.noSuchMethod(
        Invocation.getter(#loadProgress),
        returnValue: _i4.Stream<double>.empty(),
        returnValueForMissingStub: _i4.Stream<double>.empty(),
      ) as _i4.Stream<double>);

  @override
  bool get isGenerating => (super.noSuchMethod(
        Invocation.getter(#isGenerating),
        returnValue: false,
        returnValueForMissingStub: false,
      ) as bool);

  @override
  _i4.Future<void> loadModel({
    required String? modelPath,
    int? threads = 4,
    int? contextSize = 2048,
    int? gpuLayers,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #loadModel,
          [],
          {
            #modelPath: modelPath,
            #threads: threads,
            #contextSize: contextSize,
            #gpuLayers: gpuLayers,
          },
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Stream<String> generate({
    required String? prompt,
    int? maxTokens = 512,
    double? temperature = 0.7,
    double? topP = 0.9,
    int? topK = 40,
    double? minP = 0.05,
    double? typicalP = 1.0,
    double? repeatPenalty = 1.1,
    double? frequencyPenalty = 0.0,
    double? presencePenalty = 0.0,
    int? repeatLastN = 64,
    int? mirostat = 0,
    double? mirostatTau = 5.0,
    double? mirostatEta = 0.1,
    int? seed,
    bool? penalizeNewline = true,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #generate,
          [],
          {
            #prompt: prompt,
            #maxTokens: maxTokens,
            #temperature: temperature,
            #topP: topP,
            #topK: topK,
            #minP: minP,
            #typicalP: typicalP,
            #repeatPenalty: repeatPenalty,
            #frequencyPenalty: frequencyPenalty,
            #presencePenalty: presencePenalty,
            #repeatLastN: repeatLastN,
            #mirostat: mirostat,
            #mirostatTau: mirostatTau,
            #mirostatEta: mirostatEta,
            #seed: seed,
            #penalizeNewline: penalizeNewline,
          },
        ),
        returnValue: _i4.Stream<String>.empty(),
        returnValueForMissingStub: _i4.Stream<String>.empty(),
      ) as _i4.Stream<String>);

  @override
  _i4.Future<void> stop() => (super.noSuchMethod(
        Invocation.method(
          #stop,
          [],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<void> dispose() => (super.noSuchMethod(
        Invocation.method(
          #dispose,
          [],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<bool> isModelLoaded() => (super.noSuchMethod(
        Invocation.method(
          #isModelLoaded,
          [],
        ),
        returnValue: _i4.Future<bool>.value(false),
        returnValueForMissingStub: _i4.Future<bool>.value(false),
      ) as _i4.Future<bool>);

  @override
  _i4.Future<List<String>> getSupportedTemplates() => (super.noSuchMethod(
        Invocation.method(
          #getSupportedTemplates,
          [],
        ),
        returnValue: _i4.Future<List<String>>.value(<String>[]),
        returnValueForMissingStub: _i4.Future<List<String>>.value(<String>[]),
      ) as _i4.Future<List<String>>);

  @override
  _i4.Stream<String> generateChat({
    required List<_i2.ChatMessage>? messages,
    String? template,
    int? maxTokens = 512,
    double? temperature = 0.7,
    double? topP = 0.9,
    int? topK = 40,
    double? minP = 0.05,
    double? typicalP = 1.0,
    double? repeatPenalty = 1.1,
    double? frequencyPenalty = 0.0,
    double? presencePenalty = 0.0,
    int? repeatLastN = 64,
    int? mirostat = 0,
    double? mirostatTau = 5.0,
    double? mirostatEta = 0.1,
    int? seed,
    bool? penalizeNewline = true,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #generateChat,
          [],
          {
            #messages: messages,
            #template: template,
            #maxTokens: maxTokens,
            #temperature: temperature,
            #topP: topP,
            #topK: topK,
            #minP: minP,
            #typicalP: typicalP,
            #repeatPenalty: repeatPenalty,
            #frequencyPenalty: frequencyPenalty,
            #presencePenalty: presencePenalty,
            #repeatLastN: repeatLastN,
            #mirostat: mirostat,
            #mirostatTau: mirostatTau,
            #mirostatEta: mirostatEta,
            #seed: seed,
            #penalizeNewline: penalizeNewline,
          },
        ),
        returnValue: _i4.Stream<String>.empty(),
        returnValueForMissingStub: _i4.Stream<String>.empty(),
      ) as _i4.Stream<String>);

  @override
  _i4.Future<_i2.ContextInfo> getContextInfo() => (super.noSuchMethod(
        Invocation.method(
          #getContextInfo,
          [],
        ),
        returnValue: _i4.Future<_i2.ContextInfo>.value(_FakeContextInfo_0(
          this,
          Invocation.method(
            #getContextInfo,
            [],
          ),
        )),
        returnValueForMissingStub:
            _i4.Future<_i2.ContextInfo>.value(_FakeContextInfo_0(
          this,
          Invocation.method(
            #getContextInfo,
            [],
          ),
        )),
      ) as _i4.Future<_i2.ContextInfo>);

  @override
  _i4.Future<void> clearContext() => (super.noSuchMethod(
        Invocation.method(
          #clearContext,
          [],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  void setSystemPromptLength(int? length) => super.noSuchMethod(
        Invocation.method(
          #setSystemPromptLength,
          [length],
        ),
        returnValueForMissingStub: null,
      );

  @override
  _i4.Future<void> registerCustomTemplate(
    String? name,
    String? content,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #registerCustomTemplate,
          [
            name,
            content,
          ],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<void> unregisterCustomTemplate(String? name) =>
      (super.noSuchMethod(
        Invocation.method(
          #unregisterCustomTemplate,
          [name],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  void onToken(String? token) => super.noSuchMethod(
        Invocation.method(
          #onToken,
          [token],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void onDone() => super.noSuchMethod(
        Invocation.method(
          #onDone,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void onError(String? error) => super.noSuchMethod(
        Invocation.method(
          #onError,
          [error],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void onLoadProgress(double? progress) => super.noSuchMethod(
        Invocation.method(
          #onLoadProgress,
          [progress],
        ),
        returnValueForMissingStub: null,
      );
}
